In [18]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score
import joblib

In [19]:
df=pd.read_csv("C:/Users/Durga/OneDrive/Desktop/DataScience/ExpenseAnalyser/OpTransactionHistory26-04-2026.csv",encoding="ISO-8859-1")

In [20]:
df

,ï»¿S No.,Value Date,Transaction Date,Cheque Number,Transaction Remarks,Withdrawal Amount(INR),Deposit Amount(INR),Balance(INR)
0,1.0,01-04-2026,01-04-2026,NaN,UPI/HDFC BANK/hdfcbank.billd/Pay/HDFC BANK/609...,8000.00,0.0,116045.48
1,2.0,02-04-2026,02-04-2026,NaN,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,2000.00,0.0,114045.48
2,3.0,02-04-2026,02-04-2026,NaN,UPI/Swiggy Lim/swiggy1online./UPI/AXIS BANK/64...,1392.00,0.0,112653.48
3,4.0,02-04-2026,02-04-2026,NaN,UPI/Google Ind/gpay.bp.rechar/UPI/AXIS BANK/60...,148.90,0.0,112504.58
4,5.0,03-04-2026,03-04-2026,NaN,BIL/Consumer Loan XX91439 EMI Durg,10125.00,0.0,102379.58
5,6.0,04-04-2026,04-04-2026,NaN,UPI/SRI VENKAT/0514700a006723/UPI/Punjab Nat/6...,750.00,0.0,101629.58
6,7.0,04-04-2026,04-04-2026,NaN,UPI/Swiggy Ltd/swiggyupi@axb/UPI/AXIS BANK/646...,1370.00,0.0,100259.58
7,8.0,04-04-2026,04-04-2026,NaN,BIL/NEFT/IN12609431496564/TVH MAHANY/CITY UNIO...,15000.00,0.0,85259.58
8,9.0,04-04-2026,04-04-2026,NaN,BIL/NEFT/IN12609431496812/Rent/V Malini A/UCO ...,8000.00,0.0,77259.58
9,10.0,04-04-2026,04-04-2026,NaN,UPI/srividhyak/srividhyakamal/UPI/UNION BANK/6...,2209.00,0.0,75050.58
10,11.0,04-04-2026,04-04-2026,NaN,UPI/Amazon Ind/amazon.refunds/Refund for/YES B...,0.00,699.0,75749.58
11,12.0,04-04-2026,04-04-2026,NaN,UPI/PRASHANTH/vyapar.1741807/UPI/HDFC BANK/646...,600.00,0.0,75149.58
12,13.0,04-04-2026,04-04-2026,NaN,UPI/PRASHANTH/prashanthhospi/UPI/HDFC BANK/646...,715.52,0.0,74434.06
13,14.0,05-04-2026,05-04-2026,NaN,UPI/APOLLO PHA/apollopharmacy/UPIIntent/AXIS B...,1269.98,0.0,73164.08
14,15.0,05-04-2026,05-04-2026,NaN,UPI/apollophar/apollopharmacy/RRRPPPL280/AXIS ...,0.00,279.2,73443.28
15,16.0,06-04-2026,06-04-2026,NaN,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,2000.00,0.0,71443.28
16,17.0,06-04-2026,06-04-2026,NaN,UPI/SRI VENKAT/0514700a006723/UPI/Punjab,795.00,0.0,70648.28
17,NaN,NaN,NaN,NaN,Nat/609626743380/ICIac0abdff4dcb46b0851bbe9eb9...,NaN,NaN,NaN
18,18.0,07-04-2026,07-04-2026,NaN,UPI/MANIKANDAN/g.manikandan24/UPI/AXIS BANK/64...,10000.00,0.0,60648.28
19,19.0,08-04-2026,08-04-2026,NaN,UPI/APPLE MEDI/appleservices./Execution/HDFC B...,75.00,0.0,60573.28
20,20.0,08-04-2026,08-04-2026,NaN,UPI/Meesho/paytm-17731298/OidmeeshoN/YES BANK ...,221.00,0.0,60352.28
21,21.0,08-04-2026,08-04-2026,NaN,UPI/APPLE MEDI/appleservices./Execution/HDFC B...,699.00,0.0,59653.28
22,22.0,09-04-2026,09-04-2026,NaN,UPI/SWIGGY LIM/swiggyinstamar/UPI/AXIS BANK/60...,537.00,0.0,59116.28
23,23.0,10-04-2026,10-04-2026,NaN,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,2500.00,0.0,56616.28
24,24.0,10-04-2026,10-04-2026,NaN,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,5000.00,0.0,51616.28
25,25.0,10-04-2026,10-04-2026,NaN,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,2500.00,0.0,49116.28
26,26.0,10-04-2026,10-04-2026,NaN,UPI/Swiggy Lim/swiggy.stores@/UPI/AXIS BANK/64...,495.00,0.0,48621.28
27,27.0,10-04-2026,10-04-2026,NaN,UPI/Ganga Swee/q487021357@ybl/UPI/YES BANK L/6...,294.00,0.0,48327.28
28,28.0,12-04-2026,12-04-2026,NaN,UPI/WWW MYNTRA/myntra2.payu@h/UPIIntent/HDFC B...,6819.00,0.0,41508.28
29,29.0,13-04-2026,13-04-2026,NaN,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,2500.00,0.0,39008.28
30,30.0,13-04-2026,13-04-2026,NaN,UPI/TEAM COMPU/pinelabs.10167/Paymentfor/HDFC ...,1789.00,0.0,37219.28
31,31.0,16-04-2026,16-04-2026,NaN,UPI/Amazon Ind/amazon@yapl/You are pa/YES BANK...,304.00,0.0,36915.28
32,32.0,17-04-2026,17-04-2026,NaN,EBA/MFP-8512497646-214404007-S-1271993-220820282,2000.00,0.0,34915.28
33,33.0,17-04-2026,17-04-2026,NaN,UPI/DURGA R/durga.manikand/fees/State Bank/610...,0.00,50000.0,84915.28
34,34.0,17-04-2026,17-04-2026,NaN,BIL/INFT/FDL1022420/ShivanishreeM/ ...,64900.00,0.0,20015.28
35,35.0,17-04-2026,17-04-2026,NaN,UPI/WWW MYNTRA/myntra2.payu@h/Refund/HDFC BANK...,0.00,1246.0,21261.28
36,36.0,18-04-2026,18-04-2026,NaN,UPI/SWIGGY INS/swiggyinstamar/UPI/ICICI Bank/6...,423.00,0.0,20838.28
37,37.0,19-04-2026,19-04-2026,NaN,UPI/Swiggy Lim/swiggy1online./UPI/AXIS BANK/61...,831.00,0.0,20007.28
38,38.0,19-04-2026,19-04-2026,NaN,UPI/Swiggy Ltd/swiggyupi@axb/UPI/AXIS BANK/610...,730.00,0.0,19277.28
39,39.0,20-04-2026,20-04-2026,NaN,BIL/BPAY/0000001R2VDR/BBPS/TATA Play/,500.00,0.0,18777.28
40,40.0,20-04-2026,20-04-2026,NaN,EBA/EQ Trade 20APR/20260420170210,5688.32,0.0,13088.96
41,41.0,21-04-2026,21-04-2026,NaN,EBA/EQ Trade 21APR/20260421060034,5.91,0.0,13083.05
42,42.0,21-04-2026,21-04-2026,NaN,EBA/FreeCardRfnd/20260421073553,0.00,4.7,13087.75
43,43.0,22-04-2026,22-04-2026,NaN,UPI/SWIGGY/upiswiggy@icic/UPI/ICICI Bank/61128...,480.00,0.0,12607.75
44,44.0,24-04-2026,24-04-2026,NaN,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,1500.00,0.0,11107.75
45,45.0,25-04-2026,25-04-2026,NaN,UPI/Swiss Emma/9810959577-1@o/UPI/AXIS BANK/61...,500.00,0.0,10607.75
46,46.0,26-04-2026,26-04-2026,NaN,Int on FD/RD XXX6000 Tds:0. ...,0.00,2652.0,13259.75
47,47.0,26-04-2026,26-04-2026,NaN,UPI/Swiggy Ltd/swiggyupi@axb/UPI/AXIS BANK/648...,832.00,0.0,12427.75
48,48.0,26-04-2026,26-04-2026,NaN,UPI/Swiggy Lim/swiggy.refunds/OrderCance/AXIS ...,0.00,832.0,13259.75

In [21]:
df.columns

Index(['ï»¿S No.', 'Value Date', 'Transaction Date', 'Cheque Number',
       'Transaction Remarks', 'Withdrawal Amount(INR)', 'Deposit Amount(INR)',
       'Balance(INR)'],
      dtype='str')

In [22]:
df.drop(['Cheque Number'], axis=1, inplace=True)

In [23]:
df

,ï»¿S No.,Value Date,Transaction Date,Transaction Remarks,Withdrawal Amount(INR),Deposit Amount(INR),Balance(INR)
0,1.0,01-04-2026,01-04-2026,UPI/HDFC BANK/hdfcbank.billd/Pay/HDFC BANK/609...,8000.00,0.0,116045.48
1,2.0,02-04-2026,02-04-2026,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,2000.00,0.0,114045.48
2,3.0,02-04-2026,02-04-2026,UPI/Swiggy Lim/swiggy1online./UPI/AXIS BANK/64...,1392.00,0.0,112653.48
3,4.0,02-04-2026,02-04-2026,UPI/Google Ind/gpay.bp.rechar/UPI/AXIS BANK/60...,148.90,0.0,112504.58
4,5.0,03-04-2026,03-04-2026,BIL/Consumer Loan XX91439 EMI Durg,10125.00,0.0,102379.58
5,6.0,04-04-2026,04-04-2026,UPI/SRI VENKAT/0514700a006723/UPI/Punjab Nat/6...,750.00,0.0,101629.58
6,7.0,04-04-2026,04-04-2026,UPI/Swiggy Ltd/swiggyupi@axb/UPI/AXIS BANK/646...,1370.00,0.0,100259.58
7,8.0,04-04-2026,04-04-2026,BIL/NEFT/IN12609431496564/TVH MAHANY/CITY UNIO...,15000.00,0.0,85259.58
8,9.0,04-04-2026,04-04-2026,BIL/NEFT/IN12609431496812/Rent/V Malini A/UCO ...,8000.00,0.0,77259.58
9,10.0,04-04-2026,04-04-2026,UPI/srividhyak/srividhyakamal/UPI/UNION BANK/6...,2209.00,0.0,75050.58
10,11.0,04-04-2026,04-04-2026,UPI/Amazon Ind/amazon.refunds/Refund for/YES B...,0.00,699.0,75749.58
11,12.0,04-04-2026,04-04-2026,UPI/PRASHANTH/vyapar.1741807/UPI/HDFC BANK/646...,600.00,0.0,75149.58
12,13.0,04-04-2026,04-04-2026,UPI/PRASHANTH/prashanthhospi/UPI/HDFC BANK/646...,715.52,0.0,74434.06
13,14.0,05-04-2026,05-04-2026,UPI/APOLLO PHA/apollopharmacy/UPIIntent/AXIS B...,1269.98,0.0,73164.08
14,15.0,05-04-2026,05-04-2026,UPI/apollophar/apollopharmacy/RRRPPPL280/AXIS ...,0.00,279.2,73443.28
15,16.0,06-04-2026,06-04-2026,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,2000.00,0.0,71443.28
16,17.0,06-04-2026,06-04-2026,UPI/SRI VENKAT/0514700a006723/UPI/Punjab,795.00,0.0,70648.28
17,NaN,NaN,NaN,Nat/609626743380/ICIac0abdff4dcb46b0851bbe9eb9...,NaN,NaN,NaN
18,18.0,07-04-2026,07-04-2026,UPI/MANIKANDAN/g.manikandan24/UPI/AXIS BANK/64...,10000.00,0.0,60648.28
19,19.0,08-04-2026,08-04-2026,UPI/APPLE MEDI/appleservices./Execution/HDFC B...,75.00,0.0,60573.28
20,20.0,08-04-2026,08-04-2026,UPI/Meesho/paytm-17731298/OidmeeshoN/YES BANK ...,221.00,0.0,60352.28
21,21.0,08-04-2026,08-04-2026,UPI/APPLE MEDI/appleservices./Execution/HDFC B...,699.00,0.0,59653.28
22,22.0,09-04-2026,09-04-2026,UPI/SWIGGY LIM/swiggyinstamar/UPI/AXIS BANK/60...,537.00,0.0,59116.28
23,23.0,10-04-2026,10-04-2026,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,2500.00,0.0,56616.28
24,24.0,10-04-2026,10-04-2026,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,5000.00,0.0,51616.28
25,25.0,10-04-2026,10-04-2026,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,2500.00,0.0,49116.28
26,26.0,10-04-2026,10-04-2026,UPI/Swiggy Lim/swiggy.stores@/UPI/AXIS BANK/64...,495.00,0.0,48621.28
27,27.0,10-04-2026,10-04-2026,UPI/Ganga Swee/q487021357@ybl/UPI/YES BANK L/6...,294.00,0.0,48327.28
28,28.0,12-04-2026,12-04-2026,UPI/WWW MYNTRA/myntra2.payu@h/UPIIntent/HDFC B...,6819.00,0.0,41508.28
29,29.0,13-04-2026,13-04-2026,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,2500.00,0.0,39008.28
30,30.0,13-04-2026,13-04-2026,UPI/TEAM COMPU/pinelabs.10167/Paymentfor/HDFC ...,1789.00,0.0,37219.28
31,31.0,16-04-2026,16-04-2026,UPI/Amazon Ind/amazon@yapl/You are pa/YES BANK...,304.00,0.0,36915.28
32,32.0,17-04-2026,17-04-2026,EBA/MFP-8512497646-214404007-S-1271993-220820282,2000.00,0.0,34915.28
33,33.0,17-04-2026,17-04-2026,UPI/DURGA R/durga.manikand/fees/State Bank/610...,0.00,50000.0,84915.28
34,34.0,17-04-2026,17-04-2026,BIL/INFT/FDL1022420/ShivanishreeM/ ...,64900.00,0.0,20015.28
35,35.0,17-04-2026,17-04-2026,UPI/WWW MYNTRA/myntra2.payu@h/Refund/HDFC BANK...,0.00,1246.0,21261.28
36,36.0,18-04-2026,18-04-2026,UPI/SWIGGY INS/swiggyinstamar/UPI/ICICI Bank/6...,423.00,0.0,20838.28
37,37.0,19-04-2026,19-04-2026,UPI/Swiggy Lim/swiggy1online./UPI/AXIS BANK/61...,831.00,0.0,20007.28
38,38.0,19-04-2026,19-04-2026,UPI/Swiggy Ltd/swiggyupi@axb/UPI/AXIS BANK/610...,730.00,0.0,19277.28
39,39.0,20-04-2026,20-04-2026,BIL/BPAY/0000001R2VDR/BBPS/TATA Play/,500.00,0.0,18777.28
40,40.0,20-04-2026,20-04-2026,EBA/EQ Trade 20APR/20260420170210,5688.32,0.0,13088.96
41,41.0,21-04-2026,21-04-2026,EBA/EQ Trade 21APR/20260421060034,5.91,0.0,13083.05
42,42.0,21-04-2026,21-04-2026,EBA/FreeCardRfnd/20260421073553,0.00,4.7,13087.75
43,43.0,22-04-2026,22-04-2026,UPI/SWIGGY/upiswiggy@icic/UPI/ICICI Bank/61128...,480.00,0.0,12607.75
44,44.0,24-04-2026,24-04-2026,ACH/TP ACH INDIANESIGN/ICIC7022208230013669/21...,1500.00,0.0,11107.75
45,45.0,25-04-2026,25-04-2026,UPI/Swiss Emma/9810959577-1@o/UPI/AXIS BANK/61...,500.00,0.0,10607.75
46,46.0,26-04-2026,26-04-2026,Int on FD/RD XXX6000 Tds:0. ...,0.00,2652.0,13259.75
47,47.0,26-04-2026,26-04-2026,UPI/Swiggy Ltd/swiggyupi@axb/UPI/AXIS BANK/648...,832.00,0.0,12427.75
48,48.0,26-04-2026,26-04-2026,UPI/Swiggy Lim/swiggy.refunds/OrderCance/AXIS ...,0.00,832.0,13259.75

In [24]:
df["Transaction Remarks"] = df["Transaction Remarks"].str.lower().str.strip()

In [25]:
df.head()

,ï»¿S No.,Value Date,Transaction Date,Transaction Remarks,Withdrawal Amount(INR),Deposit Amount(INR),Balance(INR)
0,1.0,01-04-2026,01-04-2026,upi/hdfc bank/hdfcbank.billd/pay/hdfc bank/609...,8000.0,0.0,116045.48
1,2.0,02-04-2026,02-04-2026,ach/tp ach indianesign/icic7022208230013669/21...,2000.0,0.0,114045.48
2,3.0,02-04-2026,02-04-2026,upi/swiggy lim/swiggy1online./upi/axis bank/64...,1392.0,0.0,112653.48
3,4.0,02-04-2026,02-04-2026,upi/google ind/gpay.bp.rechar/upi/axis bank/60...,148.9,0.0,112504.58
4,5.0,03-04-2026,03-04-2026,bil/consumer loan xx91439 emi durg,10125.0,0.0,102379.58

In [26]:
def categorize(text):
    text = str(text).lower().strip()

    if any(word in text for word in ["swiggy", "zomato", "restaurant", "bigbasket"]):
        return "Food"
    elif any(word in text for word in ["amazon", "flipkart", "meesho", "ajio", "myntra"]):
        return "Shopping"
    elif any(word in text for word in ["uber", "ola", "fuel", "petrol"]):
        return "Transport"
    elif any(word in text for word in ["netflix", "prime", "apple"]):
        return "Entertainment"
    elif any(word in text for word in ["atm", "withdrawal", "cash"]):
        return "Cash Withdrawal"
    elif any(word in text for word in ["salary", "interest"]):
        return "Income"
    elif any(word in text for word in ["indianesign", "eba", "sbilife"]):
        return "Investment"
    elif any(word in text for word in ["emi", "loan","school","rent","apollo"]):
        return "Bills & Payments"
    else:
        return "Others"

In [27]:

# Apply to your dataframe
df["Category"] = df["Transaction Remarks"].apply(categorize)

In [28]:
df

,ï»¿S No.,Value Date,Transaction Date,Transaction Remarks,Withdrawal Amount(INR),Deposit Amount(INR),Balance(INR),Category
0,1.0,01-04-2026,01-04-2026,upi/hdfc bank/hdfcbank.billd/pay/hdfc bank/609...,8000.00,0.0,116045.48,Others
1,2.0,02-04-2026,02-04-2026,ach/tp ach indianesign/icic7022208230013669/21...,2000.00,0.0,114045.48,Investment
2,3.0,02-04-2026,02-04-2026,upi/swiggy lim/swiggy1online./upi/axis bank/64...,1392.00,0.0,112653.48,Food
3,4.0,02-04-2026,02-04-2026,upi/google ind/gpay.bp.rechar/upi/axis bank/60...,148.90,0.0,112504.58,Others
4,5.0,03-04-2026,03-04-2026,bil/consumer loan xx91439 emi durg,10125.00,0.0,102379.58,Bills & Payments
5,6.0,04-04-2026,04-04-2026,upi/sri venkat/0514700a006723/upi/punjab nat/6...,750.00,0.0,101629.58,Others
6,7.0,04-04-2026,04-04-2026,upi/swiggy ltd/swiggyupi@axb/upi/axis bank/646...,1370.00,0.0,100259.58,Food
7,8.0,04-04-2026,04-04-2026,bil/neft/in12609431496564/tvh mahany/city unio...,15000.00,0.0,85259.58,Others
8,9.0,04-04-2026,04-04-2026,bil/neft/in12609431496812/rent/v malini a/uco ...,8000.00,0.0,77259.58,Bills & Payments
9,10.0,04-04-2026,04-04-2026,upi/srividhyak/srividhyakamal/upi/union bank/6...,2209.00,0.0,75050.58,Others
10,11.0,04-04-2026,04-04-2026,upi/amazon ind/amazon.refunds/refund for/yes b...,0.00,699.0,75749.58,Shopping
11,12.0,04-04-2026,04-04-2026,upi/prashanth/vyapar.1741807/upi/hdfc bank/646...,600.00,0.0,75149.58,Others
12,13.0,04-04-2026,04-04-2026,upi/prashanth/prashanthhospi/upi/hdfc bank/646...,715.52,0.0,74434.06,Others
13,14.0,05-04-2026,05-04-2026,upi/apollo pha/apollopharmacy/upiintent/axis b...,1269.98,0.0,73164.08,Bills & Payments
14,15.0,05-04-2026,05-04-2026,upi/apollophar/apollopharmacy/rrrpppl280/axis ...,0.00,279.2,73443.28,Bills & Payments
15,16.0,06-04-2026,06-04-2026,ach/tp ach indianesign/icic7022208230013669/21...,2000.00,0.0,71443.28,Investment
16,17.0,06-04-2026,06-04-2026,upi/sri venkat/0514700a006723/upi/punjab,795.00,0.0,70648.28,Others
17,NaN,NaN,NaN,nat/609626743380/iciac0abdff4dcb46b0851bbe9eb9...,NaN,NaN,NaN,Others
18,18.0,07-04-2026,07-04-2026,upi/manikandan/g.manikandan24/upi/axis bank/64...,10000.00,0.0,60648.28,Others
19,19.0,08-04-2026,08-04-2026,upi/apple medi/appleservices./execution/hdfc b...,75.00,0.0,60573.28,Entertainment
20,20.0,08-04-2026,08-04-2026,upi/meesho/paytm-17731298/oidmeeshon/yes bank ...,221.00,0.0,60352.28,Shopping
21,21.0,08-04-2026,08-04-2026,upi/apple medi/appleservices./execution/hdfc b...,699.00,0.0,59653.28,Entertainment
22,22.0,09-04-2026,09-04-2026,upi/swiggy lim/swiggyinstamar/upi/axis bank/60...,537.00,0.0,59116.28,Food
23,23.0,10-04-2026,10-04-2026,ach/tp ach indianesign/icic7022208230013669/21...,2500.00,0.0,56616.28,Investment
24,24.0,10-04-2026,10-04-2026,ach/tp ach indianesign/icic7022208230013669/21...,5000.00,0.0,51616.28,Investment
25,25.0,10-04-2026,10-04-2026,ach/tp ach indianesign/icic7022208230013669/21...,2500.00,0.0,49116.28,Investment
26,26.0,10-04-2026,10-04-2026,upi/swiggy lim/swiggy.stores@/upi/axis bank/64...,495.00,0.0,48621.28,Food
27,27.0,10-04-2026,10-04-2026,upi/ganga swee/q487021357@ybl/upi/yes bank l/6...,294.00,0.0,48327.28,Others
28,28.0,12-04-2026,12-04-2026,upi/www myntra/myntra2.payu@h/upiintent/hdfc b...,6819.00,0.0,41508.28,Shopping
29,29.0,13-04-2026,13-04-2026,ach/tp ach indianesign/icic7022208230013669/21...,2500.00,0.0,39008.28,Investment
30,30.0,13-04-2026,13-04-2026,upi/team compu/pinelabs.10167/paymentfor/hdfc ...,1789.00,0.0,37219.28,Others
31,31.0,16-04-2026,16-04-2026,upi/amazon ind/amazon@yapl/you are pa/yes bank...,304.00,0.0,36915.28,Shopping
32,32.0,17-04-2026,17-04-2026,eba/mfp-8512497646-214404007-s-1271993-220820282,2000.00,0.0,34915.28,Investment
33,33.0,17-04-2026,17-04-2026,upi/durga r/durga.manikand/fees/state bank/610...,0.00,50000.0,84915.28,Others
34,34.0,17-04-2026,17-04-2026,bil/inft/fdl1022420/shivanishreem/ ...,64900.00,0.0,20015.28,Others
35,35.0,17-04-2026,17-04-2026,upi/www myntra/myntra2.payu@h/refund/hdfc bank...,0.00,1246.0,21261.28,Shopping
36,36.0,18-04-2026,18-04-2026,upi/swiggy ins/swiggyinstamar/upi/icici bank/6...,423.00,0.0,20838.28,Food
37,37.0,19-04-2026,19-04-2026,upi/swiggy lim/swiggy1online./upi/axis bank/61...,831.00,0.0,20007.28,Food
38,38.0,19-04-2026,19-04-2026,upi/swiggy ltd/swiggyupi@axb/upi/axis bank/610...,730.00,0.0,19277.28,Food
39,39.0,20-04-2026,20-04-2026,bil/bpay/0000001r2vdr/bbps/tata play/,500.00,0.0,18777.28,Others
40,40.0,20-04-2026,20-04-2026,eba/eq trade 20apr/20260420170210,5688.32,0.0,13088.96,Investment
41,41.0,21-04-2026,21-04-2026,eba/eq trade 21apr/20260421060034,5.91,0.0,13083.05,Investment
42,42.0,21-04-2026,21-04-2026,eba/freecardrfnd/20260421073553,0.00,4.7,13087.75,Investment
43,43.0,22-04-2026,22-04-2026,upi/swiggy/upiswiggy@icic/upi/icici bank/61128...,480.00,0.0,12607.75,Food
44,44.0,24-04-2026,24-04-2026,ach/tp ach indianesign/icic7022208230013669/21...,1500.00,0.0,11107.75,Investment
45,45.0,25-04-2026,25-04-2026,upi/swiss emma/9810959577-1@o/upi/axis bank/61...,500.00,0.0,10607.75,Others
46,46.0,26-04-2026,26-04-2026,int on fd/rd xxx6000 tds:0. ...,0.00,2652.0,13259.75,Others
47,47.0,26-04-2026,26-04-2026,upi/swiggy ltd/swiggyupi@axb/upi/axis bank/648...,832.00,0.0,12427.75,Food
48,48.0,26-04-2026,26-04-2026,upi/swiggy lim/swiggy.refunds/ordercance/axis ...,0.00,832.0,13259.75,Food

In [29]:
df = df.dropna()

In [30]:
df.columns

Index(['ï»¿S No.', 'Value Date', 'Transaction Date', 'Transaction Remarks',
       'Withdrawal Amount(INR)', 'Deposit Amount(INR)', 'Balance(INR)',
       'Category'],
      dtype='str')

In [31]:
# Features & target
X = df["Transaction Remarks"]
y = df["Category"]

In [32]:
# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [33]:
# Pipeline
model = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2), min_df=2)),
    ("clf", LogisticRegression(max_iter=1000))
])

In [34]:
# Train
model.fit(X_train, y_train)

Pipeline(steps=[('tfidf', TfidfVectorizer(min_df=2, ngram_range=(1, 2))),
                ('clf', LogisticRegression(max_iter=1000))])

In [35]:
# Predict
y_pred = model.predict(X_test)

In [36]:
# Evaluate
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.7
                  precision    recall  f1-score   support

Bills & Payments       0.00      0.00      0.00         1
            Food       1.00      1.00      1.00         2
      Investment       1.00      1.00      1.00         3
          Others       0.40      1.00      0.57         2
        Shopping       0.00      0.00      0.00         2

        accuracy                           0.70        10
       macro avg       0.48      0.60      0.51        10
    weighted avg       0.58      0.70      0.61        10

c:\Users\Durga\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Durga\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\Durga\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [37]:
# Save model
joblib.dump(model, "C:/Users/Durga/OneDrive/Desktop/DataScience/ExpenseAnalyser/expense_model2.pkl")

['C:/Users/Durga/OneDrive/Desktop/DataScience/ExpenseAnalyser/expense_model2.pkl']